package Mavlink2::Constants;

use strict;
use warnings;
use base qw(Exporter);

use constant {

    # General
    MAVLINK_VERSION => 2,
    SIGNATURE       => 0x55,

    # MAV Type
    MAV_GENERIC    => 0,
    MAV_FIXED_WING => 1,
    MAV_QUADROTOR  => 2,
    MAV_COAXIAL    => 3,
    MAV_HELICOPTER => 4,
    MAV_GROUND     => 5,
    OCU            => 6,

    # MAV Autopilot Type
    MAV_AUTOPILOT_GENERIC       => 0,
    MAV_AUTOPILOT_PIXHAWK       => 1,
    MAV_AUTOPILOT_SLUGS         => 2,
    MAV_AUTOPILOT_ARDUPILOTMEGA => 3,

    # MAV Mode
    MAV_MODE_UNINIT      => 0,
    MAV_MODE_LOCKED      => 1,
    MAV_MODE_MANUAL      => 2,
    MAV_MODE_GUIDED      => 3,
    MAV_MODE_AUTO        => 4,
    MAV_MODE_TEST1       => 5,
    MAV_MODE_TEST2       => 6,
    MAV_MODE_TEST3       => 7,
    MAV_MODE_READY       => 8,
    MAV_MODE_RC_TRAINING => 9,

    #MAV State
    MAV_STATE_UNINIT      => 0,
    MAV_STATE_BOOT        => 1,
    MAV_STATE_CALIBRATING => 2,
    MAV_STATE_STANDBY     => 3,
    MAV_STATE_ACTIVE      => 4,
    MAV_STATE_CRITICAL    => 5,
    MAV_STATE_EMERGENCY   => 6,
    MAV_STATE_HILSIM      => 7,
    MAV_STATE_POWEROFF    => 8,

    #MAV Navigation
    MAV_NAV_GROUNDED  => 0,
    MAV_NAV_LIFTOFF   => 1,
    MAV_NAV_HOLD      => 2,
    MAV_NAV_WAYPOINT  => 3,
    MAV_NAV_VECTOR    => 4,
    MAV_NAV_RETURNING => 5,
    MAV_NAV_LANDING   => 6,
    MAV_NAV_LOST      => 7,
    MAV_NAV_LOITER    => 8
};

our @EXPORT = qw(
  MAVLINK_VERSION SIGNATURE

  MAV_GENERIC MAV_FIXED_WING MAV_QUADROTOR
  MAV_COAXIAL MAV_HELICOPTER MAV_GROUND OCU

  MAV_AUTOPILOT_GENERIC MAV_AUTOPILOT_PIXHAWK
  MAV_AUTOPILOT_SLUGS MAV_AUTOPILOT_ARDUPILOTMEGA

  MAV_MODE_UNINIT MAV_MODE_LOCKED
  MAV_MODE_MANUAL MAV_MODE_GUIDED
  MAV_MODE_AUTO   MAV_MODE_TEST1 
  MAV_MODE_TEST2  MAV_MODE_TEST3 
  MAV_MODE_READY  MAV_MODE_RC_TRAINING

  MAV_STATE_UNINIT      MAV_STATE_BOOT
  MAV_STATE_CALIBRATING MAV_STATE_STANDBY
  MAV_STATE_ACTIVE      MAV_STATE_CRITICAL
  MAV_STATE_EMERGENCY   MAV_STATE_HILSIM
  MAV_STATE_POWEROFF

  MAV_NAV_GROUNDED MAV_NAV_LIFTOFF
  MAV_NAV_HOLD     MAV_NAV_WAYPOINT
  MAV_NAV_VECTOR   MAV_NAV_RETURNING
  MAV_NAV_LANDING  MAV_NAV_LOST
  MAV_NAV_LOITER

);

1;
