package Mavlink2::Constants;

use strict;
use warnings;
use base qw(Exporter);

use constant {

    # General
    MAVLINK_VERSION => 2,
    SIGNATURE       => 0x55,

    # MAV Type
    MAV_GENERIC    => 0,
    MAV_FIXED_WING => 1,
    MAV_QUADROTOR  => 2,
    MAV_COAXIAL    => 3,
    MAV_HELICOPTER => 4,
    MAV_GROUND     => 5,
    OCU            => 6,

    # MAV Autopilot Type
    MAV_AUTOPILOT_GENERIC       => 0,
    MAV_AUTOPILOT_PIXHAWK       => 1,
    MAV_AUTOPILOT_SLUGS         => 2,
    MAV_AUTOPILOT_ARDUPILOTMEGA => 3,

    # MAV Mode
    MAV_MODE_UNINIT      => 0,
    MAV_MODE_LOCKED      => 1,
    MAV_MODE_MANUAL      => 2,
    MAV_MODE_GUIDED      => 3,
    MAV_MODE_AUTO        => 4,
    MAV_MODE_TEST1       => 5,
    MAV_MODE_TEST2       => 6,
    MAV_MODE_TEST3       => 7,
    MAV_MODE_READY       => 8,
    MAV_MODE_RC_TRAINING => 9,

    #MAV State
    MAV_STATE_UNINIT      => 0,
    MAV_STATE_BOOT        => 1,
    MAV_STATE_CALIBRATING => 2,
    MAV_STATE_STANDBY     => 3,
    MAV_STATE_ACTIVE      => 4,
    MAV_STATE_CRITICAL    => 5,
    MAV_STATE_EMERGENCY   => 6,
    MAV_STATE_HILSIM      => 7,
    MAV_STATE_POWEROFF    => 8,

    #MAV Navigation
    MAV_NAV_GROUNDED  => 0,
    MAV_NAV_LIFTOFF   => 1,
    MAV_NAV_HOLD      => 2,
    MAV_NAV_WAYPOINT  => 3,
    MAV_NAV_VECTOR    => 4,
    MAV_NAV_RETURNING => 5,
    MAV_NAV_LANDING   => 6,
    MAV_NAV_LOST      => 7,
    MAV_NAV_LOITER    => 8,

    #MAV Action
    MAV_ACTION_HOLD                 => 0,
    MAV_ACTION_MOTORS_START         => 1,
    MAV_ACTION_LAUNCH               => 2,
    MAV_ACTION_RETURN               => 3,
    MAV_ACTION_EMCY_LAND            => 4,
    MAV_ACTION_EMCY_KILL            => 5,
    MAV_ACTION_CONFIRM_KILL         => 6,
    MAV_ACTION_CONTINUE             => 7,
    MAV_ACTION_MOTORS_STOP          => 8,
    MAV_ACTION_HALT                 => 9,
    MAV_ACTION_SHUTDOWN             => 10,
    MAV_ACTION_REBOOT               => 11,
    MAV_ACTION_SET_MANUAL           => 12,
    MAV_ACTION_SET_AUTO             => 13,
    MAV_ACTION_STORAGE_READ         => 14,
    MAV_ACTION_STORAGE_WRITE        => 15,
    MAV_ACTION_CALIBRATE_RC         => 16,
    MAV_ACTION_CALIBRATE_GYRO       => 17,
    MAV_ACTION_CALIBRATE_MAG        => 18,
    MAV_ACTION_CALIBRATE_ACC        => 19,
    MAV_ACTION_CALIBRATE_PRESSURE   => 20,
    MAV_ACTION_REC_START            => 21,
    MAV_ACTION_REC_PAUSE            => 22,
    MAV_ACTION_REC_STOP             => 23,
    MAV_ACTION_TAKEOFF              => 24,
    MAV_ACTION_NAVIGATE             => 25,
    MAV_ACTION_LAND                 => 26,
    MAV_ACTION_LOITER               => 27,
    MAV_ACTION_SET_ORIGIN           => 28,
    MAV_ACTION_RELAY_ON             => 29,
    MAV_ACTION_RELAY_OFF            => 30,
    MAV_ACTION_GET_IMAGE            => 31,
    MAV_ACTION_VIDEO_START          => 32,
    MAV_ACTION_VIDEO_STOP           => 33,
    MAV_ACTION_RESET_MAP            => 34,
    MAV_ACTION_RESET_PLAN           => 35,
    MAV_ACTION_DELAY_BEFORE_COMMAND => 36,
    MAV_ACTION_ASCEND_AT_RATE       => 37,
    MAV_ACTION_CHANGE_MODE          => 38,
    MAV_ACTION_LOITER_MAX_TURNS     => 39,
    MAV_ACTION_LOITER_MAX_TIME      => 40,
    MAV_ACTION_START_HILSIM         => 41,
    MAV_ACTION_STOP_HILSIM          => 42,

    # Data Stream
    MAV_DATA_STREAM_ALL             => 0,
    MAV_DATA_STREAM_RAW_SENSORS     => 1,
    MAV_DATA_STREAM_EXTENDED_STATUS => 2,
    MAV_DATA_STREAM_RC_CHANNELS     => 3,
    MAV_DATA_STREAM_RAW_CONTROLLER  => 4,
    MAV_DATA_STREAM_POSITION        => 6,
    MAV_DATA_STREAM_EXTRA1          => 10,
    MAV_DATA_STREAM_EXTRA2          => 11,
    MAV_DATA_STREAM_EXTRA3          => 12,
};

our @EXPORT = qw(
  MAVLINK_VERSION SIGNATURE

  MAV_GENERIC MAV_FIXED_WING MAV_QUADROTOR
  MAV_COAXIAL MAV_HELICOPTER MAV_GROUND OCU

  MAV_AUTOPILOT_GENERIC MAV_AUTOPILOT_PIXHAWK
  MAV_AUTOPILOT_SLUGS MAV_AUTOPILOT_ARDUPILOTMEGA

  MAV_MODE_UNINIT MAV_MODE_LOCKED
  MAV_MODE_MANUAL MAV_MODE_GUIDED
  MAV_MODE_AUTO   MAV_MODE_TEST1
  MAV_MODE_TEST2  MAV_MODE_TEST3
  MAV_MODE_READY  MAV_MODE_RC_TRAINING

  MAV_STATE_UNINIT      MAV_STATE_BOOT
  MAV_STATE_CALIBRATING MAV_STATE_STANDBY
  MAV_STATE_ACTIVE      MAV_STATE_CRITICAL
  MAV_STATE_EMERGENCY   MAV_STATE_HILSIM
  MAV_STATE_POWEROFF

  MAV_NAV_GROUNDED MAV_NAV_LIFTOFF
  MAV_NAV_HOLD     MAV_NAV_WAYPOINT
  MAV_NAV_VECTOR   MAV_NAV_RETURNING
  MAV_NAV_LANDING  MAV_NAV_LOST
  MAV_NAV_LOITER

  MAV_ACTION_HOLD                 MAV_ACTION_MOTORS_START
  MAV_ACTION_LAUNCH               MAV_ACTION_RETURN
  MAV_ACTION_EMCY_LAND            MAV_ACTION_EMCY_KILL
  MAV_ACTION_CONFIRM_KILL         MAV_ACTION_CONTINUE
  MAV_ACTION_MOTORS_STOP          MAV_ACTION_HALT
  MAV_ACTION_SHUTDOWN             MAV_ACTION_REBOOT
  MAV_ACTION_SET_MANUAL           MAV_ACTION_SET_AUTO
  MAV_ACTION_STORAGE_READ         MAV_ACTION_STORAGE_WRITE
  MAV_ACTION_CALIBRATE_RC         MAV_ACTION_CALIBRATE_GYRO
  MAV_ACTION_CALIBRATE_MAG        MAV_ACTION_CALIBRATE_ACC
  MAV_ACTION_CALIBRATE_PRESSURE   MAV_ACTION_REC_START
  MAV_ACTION_REC_PAUSE            MAV_ACTION_REC_STOP
  MAV_ACTION_TAKEOFF              MAV_ACTION_NAVIGATE
  MAV_ACTION_LAND                 MAV_ACTION_LOITER
  MAV_ACTION_SET_ORIGIN           MAV_ACTION_RELAY_ON
  MAV_ACTION_RELAY_OFF            MAV_ACTION_GET_IMAGE
  MAV_ACTION_VIDEO_START          MAV_ACTION_VIDEO_STOP
  MAV_ACTION_RESET_MAP            MAV_ACTION_RESET_PLAN
  MAV_ACTION_DELAY_BEFORE_COMMAND MAV_ACTION_ASCEND_AT_RATE
  MAV_ACTION_CHANGE_MODE          MAV_ACTION_LOITER_MAX_TURNS
  MAV_ACTION_LOITER_MAX_TIME      MAV_ACTION_START_HILSIM
  MAV_ACTION_STOP_HILSIM

  MAV_DATA_STREAM_ALL             MAV_DATA_STREAM_RAW_SENSORS
  MAV_DATA_STREAM_EXTENDED_STATUS MAV_DATA_STREAM_RC_CHANNELS
  MAV_DATA_STREAM_RAW_CONTROLLER  MAV_DATA_STREAM_POSITION
  MAV_DATA_STREAM_EXTRA1          MAV_DATA_STREAM_EXTRA2
  MAV_DATA_STREAM_EXTRA3         

);

1;
